services:
    api:
        build: .
        container_name: tetra-master-api
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
            - API_URL=https://tetra-master-api.neverend.org
        restart: always
